export enum ActionTypes {
  LIST_FETCHED = 'LIST_FETCHED',
  LIST_LOADING_START = 'LIST_LOADING_START',
  LIST_LOADING_END = 'LIST_LOADING_END',
  USERS_FETCHED = 'USERS_FETCHED',
  USERS_LOADING_START = 'USERS_LOADING_START',
  USERS_LOADING_END = 'USERS_LOADING_END',
  COMMENTS_FETCHED = 'COMMENTS_FETCHED',
  COMMENTS_LOADING_START = 'COMMENTS_LOADING_START',
  COMMENTS_LOADING_END = 'COMMENTS_LOADING_END',
}
